//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentOrder = new HashSet<AgentOrder>();
            this.PriorityChanges = new HashSet<PriorityChanges>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> AgentTypeId { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorSurname { get; set; }
        public string DirectorName { get; set; }
        public string DirectorPatronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public Nullable<int> SuppliesPriorityID { get; set; }
        public Nullable<int> AreaSalesId { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual AreaSales AreaSales { get; set; }
        public virtual SuppliesPriority SuppliesPriority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentOrder> AgentOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriorityChanges> PriorityChanges { get; set; }
    }
}
