//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentOrder
    {
        public int Id { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductAmount { get; set; }
        public Nullable<int> DaysForProduction { get; set; }
        public Nullable<bool> PaymentPass { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
