//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Production = new HashSet<Production>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
            this.SupplieHistoryMaterial = new HashSet<SupplieHistoryMaterial>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaterialType_Id { get; set; }
        public Nullable<int> AmountPerPachage { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> PossibleSupplierId { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplieHistoryMaterial> SupplieHistoryMaterial { get; set; }
    }
}
