//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityChanges
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> StartPriority { get; set; }
        public Nullable<int> EndPriority { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SuppliesPriority SuppliesPriority { get; set; }
        public virtual SuppliesPriority SuppliesPriority1 { get; set; }
    }
}
