//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CostPrice { get; set; }
        public Nullable<int> WorshopNumber { get; set; }
        public Nullable<int> PeopleNeededForProduction { get; set; }
        public Nullable<int> MaterialId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
