//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AgentOrder = new HashSet<AgentOrder>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinPriceForAgent { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ProductType_id { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public Nullable<int> WorshopId { get; set; }
        public string Description { get; set; }
        public Nullable<int> PackageHeight { get; set; }
        public Nullable<int> PackageWeight { get; set; }
        public Nullable<int> PackageWidth { get; set; }
        public Nullable<int> PackageLength { get; set; }
        public Nullable<int> PackageWeightwithoutPacking { get; set; }
        public Nullable<int> StandartNumber { get; set; }
        public byte[] photobit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentOrder> AgentOrder { get; set; }
        public virtual Workshop Workshop { get; set; }
        public virtual productType productType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
